### ISSUE TITLE
Nitsche solid triangulation is not properly loaded

### ISSUE THREAD

**Issue by jeannejoachim** [lethe-cfd/lethe#143]
Seen during `read_checkpoint` implementation for `gls_nitsche_navier_stokes`.
For now, `load_triangulation` method in `solid_base.cc` calls `solid_tria->load(filename_tria.c_str());`, which does not allow to load all needed member variables of the triangulation (see [classTriangulation documentation of deal.ii](https://www.dealii.org/current/doxygen/deal.II/classTriangulation.html#ae2f72d5fbb277ec65dbe0382ae72a929)), resulting in a `segmentation fault` error. To avoid this error, the triangulation can be initialized with the `setup_triangulation` method, but then only the refinement is loaded, so that the Nitsche solid geometry and position are not correctly loaded for restart simulations.

A fix could be to **define a load function for the triangulation which would enable to fully load a given solid triangulation file**. The changes to apply in the code would then be :

- in `solid_base.cc`: 
- [ ] in `load_triangulation`, use the defined "full load triangulation" and update the TODO comment
- [ ] in `setup_triangulation`, remove passed boolean parameter `restart`, the loop-condition `if (!restart)` and the NB comment just above
- in `solid_base.h` :
- [ ] update the `setup_triangulation` method definition to remove the parameter `restart`
- in `gls_nitsche_navier_stokes.cc`, in the method `read_checkpoint()` :
- [ ] remove the call to `setup_triangulation`
- [ ] uncomment the call to `load_triangulation`
- [ ] remove the `pcout` lines stating "Warning - the solid triangulation cannot be properly loaded..."
- [ ] clean-up comments with `(known issue)` and `commented for now`

**Comment by blaisb** [comment]
@jeannejoachim is this still an issue?

**Comment by jeannejoachim** [comment]
I assume so, except if there has been a change in the `load` function! For now we just don't load the solid triangulation, and the restart is going well with particles only, but we loose the triangulation visualization. Do you want me to test it again?

**Comment by blaisb** [comment]
No not necessarily, because this has not changed, but maybe the issue should be streamlined to say that right now restart does not work correctly for the triangulation output?
