### ISSUE TITLE
lethe compilation issue

### ISSUE THREAD

**Issue by justAPhDStudent** [lethe-cfd/lethe#228]
There is a compilation issue for lethe; while making it shows that several header files and member  functions used are not found in dealii. May be the dealii version have changed these files. Is this an issue I only face.

**Comment by justAPhDStudent** [comment]
Error logs:
fatal error: deal.II/fe/fe_simplex_p.h: No such file or directory
   40 | #include <deal.II/fe/fe_simplex_p.h>


error: ‘convert_hypercube_to_simplex_mesh’ is not a member of ‘dealii::GridGenerator’
   84 |           GridGenerator::convert_hypercube_to_simplex_mesh(

**Comment by oguevremont** [comment]
Hello, I'll try to reproduce the error. Which dealii version are you using?

**Comment by justAPhDStudent** [comment]
I followed the Candi installation ; dealii 9.2
Thanks

**Comment by peterrum** [comment]
> I followed the Candi installation ; dealii 9.2
Thanks

Could you repeat the candi installation with the following branch: https://github.com/dealii/candi/tree/dealii-9.3? It seems that candi is still defaulted to version 9.2. However, you need at least 9.3 of deal.II.

**Comment by tjhei** [comment]
You should update the required version in cmake.

**Comment by justAPhDStudent** [comment]
Okay I will, 
The error looks like it's going to be fixed by this. I will change this in Candi and let you know soon. If worked IL will close this issue. 

Thanks very much.

**Comment by peterrum** [comment]
> You should update the required version in cmake.

That is true. @justAPhDStudent or @oguevremont Do you want to make the change in a PR?

**Comment by justAPhDStudent** [comment]
I prefer anyone in the official team do the pull request. 
I will make the changes in CMakeLists.txt too. 

Thanks.

**Comment by oguevremont** [comment]
Yes I'll do it

**Comment by justAPhDStudent** [comment]
Just an FYI, may be not so relevant. Lethe compiled and I could run some examples. Though the ctest utility failed; it showed tests as Failed. Anyhow I could run some examples manually, which is the major concern here. Just mentioning this for completeness.

**Comment by blaisb** [comment]
Is this still an open issue? @oguevremont you can make a PR with the change in the deal.II required version. When Paul reworked the CMakeList he added a nice check for the dependencies, but clearly we forgot to change the most basic thing which is the require dversion.
@justAPhDStudent Could you please tell me which tests fail when you run Ctest ? Some tests are not very portable (they work on the CI and under most distros, but we they seem to fail on some of the machines we have access to, like the Compute Canada clusters). We'd be glad to improve the tests to make them more robust. :)

**Comment by oguevremont** [comment]
I just made the PR now that the CI tests have passed :)
