### ISSUE TITLE
Not an issue, but a discussion | Robustness of the incompressible lethe solvers

### ISSUE THREAD

**Issue by justAPhDStudent** [lethe-cfd/lethe#230]
Hello,
Sorry to post here in the Issues tab of this github page; if you would have enabled the discussions tab for the community using lethe it would be really great. 

Coming to my query, I was just playing with the incompressible solvers of lethe (both transient & steady). All the examples provided along with are only basic examples. I would like to know the robustness of the lethe incompressible solvers (in comparison with its Openfoam counterparts) if you would have done some HPC solves at common Reynolds numbers involving turbulence. In the related article, I read lethe was designed with chemical engineering point of view. Does it mean, the solvers won't be good for turbulence (low speed aerodynamics: popular cars, bikes) modeling.

If you have some articles showing the robustness & scalability of lethe solvers; please pass me a reference. With p4est & trilinos backend, the solver will be scalable; but does the solver & preconditioners reliable for the aerodynamics physics.

**Comment by blaisb** [comment]
@justAPhDStudent  I opened the discussion tab if you want to use it in the future. In all cases, thanks for asking.
Lethe was mostly conceived with laminar, transitional and early turbulent flow in minds. In the original Lethe paper, we notably benchmark Lethe on the DNS flow of Taylor-Green vortices at Re=1600.  https://www.sciencedirect.com/science/article/pii/S2352711020302922
https://www.youtube.com/watch?v=klIhuInbXmQ

We notably compare the Enstrophy/Kinetic energy dissipation with reference DNS results and show that Lethe has good capabilities in reproducing results obtained in the literature. This is a simple, but effective example for a turbulent flow.
We have also benchmarked Lethe on other canonical turbulent flows (Turbulent flat plate, flow around a sphere, flow around a cylinder, flow over periodic hills). You can for example see the results for the flow over periodic hills here:
https://www.youtube.com/watch?v=rZMT1JMvQgs
@lpsaavedra will be submitting an article soon related to the results obtained with this benchmark. I can't exactly share the results right now, but they were quite conclusive. This flow is at Reynolds number of 5.6k.

So to give an honest assessment. Lethe is made mostly to work well at Re number from 0 to 50-100k or so at the moment. The stabilization method we use and the implicit LES strategy that we have chosen (which is residual based) has limitations. We are actively working on making those better, but I don't know how good (or bad things will end up). So clearly, if you are interested in very high Reynolds number (>100k), I don't think Lethe is the right tool for that at the moment.  We also don't have any RANS model. They could be added (I mean anything could be added really, that just requires time and patience).

It is not made for compressible flows, at least we don't plan on making a compressible flow solver anytime in the short/mid term.

I think that with mesh adaptation and the capacity to use high-order time-stepping schemes and high-order elements, Lethe has a good deal of flexibility. However, robustness is currently far from what you would get used OpenFOAM. A well set-up OpenFOAM case will often converge. With Lethe, the scaling of the problem and the initial condition can have more impact on the robustness of the simulation. It works well, it's pretty fast and it scales very well with the number of cores, but I would be lying to you if I told you it is robust like OpenFOAM. Another reason for that is that Lethe uses a fully implicit formulation. This leads to more sensitive linear system. However, once a problem is set-up, you won't have limitations on the CFL number and etc. A well set-up Lethe problem actually leads to a very robust solver in terms of time-stepping. OpenFOAM uses a pressure predictor-corrector schemes. These have one linear system of equation per variable (u,v,w,p) and hence, the linear systems become significantly easier to solve, at the cost of a loss of stability, loss of temporal accuracy and limitations on the value of the time-step. Again, the no free lunch theorem strikes.

I hope this gives you a good assessment of what Lethe can do at the moment. It's a free code and it is LGPL3. If you feel like it could be useful to you with additional feature, I'd be glad to talk to you about it and help you integrate them. We have a pretty nice CI and a very open review process. Everybody is welcome to join aboard. To be honest though, it is still a research code. I can't compare it to something like OpenFOAM in terms of flexibility and capacities. One is 25 years old with tons of research behind it and the other one is barely two years old. We are lucky we have the strong Deal.II backbone as a framework supporting us.
