### ISSUE TITLE
Boundry

### ISSUE THREAD

**Issue by ghazalemir** [lethe-cfd/lethe#24]
![image](https://user-images.githubusercontent.com/55454234/78574304-cee59000-77f7-11ea-881c-fc29928393c4.png)

**Comment by blaisb** [comment]
Hmm? Did you mean to do a pull request? I am not sure this is the right approach to add the image :)!

**Comment by blaisb** [comment]
You can ask Toni he has done it lately :)!

**Comment by ghazalemir** [comment]
ok :))
then I am trying a wrong way!
