### ISSUE TITLE
Installation instructions do not work on Niagara anymore because of disabled old modules

### ISSUE THREAD

**Issue by blaisb** [lethe-cfd/lethe#375]
The installation instructions of Narval must then be used on Niagara.
The installation page will need updating to take this into account.

Two additional modules are needed:
module load CCEnv
module load StdEnv/2020

**Comment by jeannejoachim** [comment]
Is this still a thing? I just updated deal.II and Lethe on Narval, using the version on the documentation website, and got no problem. I opened a PR to fix a typo on the page of the documentation, so let me know if I need to add this also.
