### ISSUE TITLE
Boundary id missing from subsection bc

### ISSUE THREAD

**Issue by blaisb** [lethe-cfd/lethe#384]
Title says it all.
A small PR to do.

**Comment by jeannejoachim** [comment]
Still missing for Boundary Conditions - Multiphysics

**Comment by blaisb** [comment]
@jeannejoachim Is this still an issue, if so I'll try to cook-up a PR for it today or tomorrow

**Comment by jeannejoachim** [comment]
Yes it is! It's not much to add though, tell me if you want me to do it, I have another part of the doc to update as well so it will not be much more extra work

https://lethe-cfd.github.io/lethe/parameters/cfd/boundary_conditions_multiphysics.html
