### ISSUE TITLE
Resolved CFD-DEM and unresolved CFD-DEM examples should be grouped into seperate folder

### ISSUE THREAD

**Issue by blaisb** [lethe-cfd/lethe#416]
Right now, there is a degree of confusion on the cfd-dem example
the unresolved examples are in examples/cfd-dem/example_name, but the unresolved examples are in examples/cfd-dem/resolved-cfd-dem/example_name.

I suggest we use a structure like:
examples/unresolved_cfd-dem/
examples/resolved_cfd-dem/
This way it will be clear from the get go.
@tonielgeitani or @Luckabarbeau I'll let you decide who takes care of that, it will be a very small PR to make.

**Comment by tonielgeitani** [comment]
A new PR has been created to resolve this issue
