### ISSUE TITLE
Nitsche solid simulation with simplex

### ISSUE THREAD

**Issue by jeannejoachim** [lethe-cfd/lethe#419]
When using a simplex mesh for both the Nitsche solid and the fluid, particles are lost at the very first iteration.

Maybe this has something to do with the mapping. I can provide files for testing that.

**Comment by jeannejoachim** [comment]
@oguevremont I assign this to you as we talked about it, we could work together on that whenever you are ready :)

**Comment by blaisb** [comment]
I'll take a look into it this week.
