### ISSUE TITLE
Test with restart files break down if p4est 2.3.2 is used

### ISSUE THREAD

**Issue by blaisb** [lethe-cfd/lethe#467]
While installing on a new machine, I realized that the tests we have do not appear to be portable from p4est 2.2 to p4est 2.3.2. This means that once the P4est version changes on the docker image of deal.II master, all tests which have a restart will break. This is not a major issue, but until the CI is changed, it means that we should only expect the restart tests to work with p4est 2.2.

Until then, we can prepare for the CI change by adding the prm files that are used to generate the restart files.
We should split this task into four.
@blaisb  will take care of the gls_navier_stokes, gd_navier_stokes and nitsche restart files
@Luckabarbeau will take care of the sharp edge restart
@tonielgeitani  will take care of the cfd-dem restart
@shahabgol will take care of the dem restarts

As long as we can prepare for that, things should be good :). Let's try to include this in seperate PR as we go during the following months.

**Comment by shahabgol** [comment]
I had saved the parameter handler files that I used for creating the restart files of DEM solver tests in Lethe-utils. Should I create new restart files using these parameter handler files now?

**Comment by blaisb** [comment]
> I had saved the parameter handler files that I used for creating the restart files of DEM solver tests in Lethe-utils. Should I create new restart files using these parameter handler files now?

Don't create new restart files, but please add these prm file to the application_test folder without any .output file so we have them in the lethe repository if we need to regenerate them. like call it test_name_checkpoint_generator.prm or something similar. This way everything will be at the same place ;)!
