### ISSUE TITLE
gls_free-surface_drop-wetting_inverted  gls_free-surface_drop-peeling are broken

### ISSUE THREAD

**Issue by blaisb** [lethe-cfd/lethe#483]
The tests break on my machine at home and break regularly on the CI
(see https://github.com/lethe-cfd/lethe/runs/6641090352?check_suite_focus=true)

Until the test is fixed and made stable, I have disabled it.
@jeannejoachim I think you were the one that wrote it? There seems to be something highly non-reproducible with that test indicating either a bug with the feature or a non-robust test.

I suggest running them through valgrind to see if they are sane

**Comment by jeannejoachim** [comment]
Hi Bruno, I had trouble to setup these tests to begin with, so I narrowed them a lot. It always passes on my machine now and it passed multiple time on the CI during my last PR review so I thought I had found a stable way of testing these mechanisms. Sorry that it was not, you were right to disable it and we can talk about is this week!
