### ISSUE TITLE
Time-averaged velocity calculation

### ISSUE THREAD

**Issue by DanW97** [lethe-cfd/lethe#511]
Hi,

I've been playing with the Nitsche mixer example, and because I've decided to give my computer some abuse then I'm looking at cranking up the rotation speed and lowering the viscosity, so I am obviously interested in the Reynolds stresses and turbulent kinetic energy. 

In lines 47-48 of [include/solvers/postprocessing_velocities.h](https://github.com/lethe-cfd/lethe/blob/5d23ff2f6649f39def55c000f7b097c7f4c52b51/include/solvers/postprocessing_velocities.h#L47) there is a comment saying that these calculations are currently available when using adaptative meshing, yet in the example provided, the Reynolds stress components *are* calculated, alongside the turbulent kinetic energy. I'm wondering if this is a comment that simply hasn't been removed yet or are these values only valid for a static mesh size?

So, am I able to ignore this comment and trust the Reynolds stress values that are calculated, or is further work still needed?

Cheers,

Dan

**Comment by blaisb** [comment]
Dear @DanW97 , 
This comment is a leftover from a time when this did not work. Currently, time-averaged velocity and Reynolds stresses can be calculated with an adaptive mesh. The only issue is that they are always "projected" or interpolated onto the final mesh. So the results you get at the end are the time-averaged velocity using the entire history of meshes onto the final one. This is an inevitable limitation of using time-averaging on a dynamic mesh, but we have found that if you leave the coarsest mesh a reasonable level, it gives very good results.

I will make a PR to remove the comments today or tomorrow  then close this issue once it's merged :)!
