### ISSUE TITLE
Moving geometries in DEM/CFD-DEM

### ISSUE THREAD

**Issue by DanW97** [lethe-cfd/lethe#543]
Hi,

Is it possible for user-created geometries (e.g. an agitator) to interact with DEM particles in either DEM or CFD-DEM simulations? I can see from the docs that I can define parameters for **a** wall, but nothing about how to define additional geometries. I'm interested in using Lethe for a stirred mill, so, ideally I would like the stirrer to be able to move and interact with the DEM particles.

Cheers,

Dan

**Comment by blaisb** [comment]
Dear Dan,
For the DEM component, moving geometries have been added something like 3-4 days ago. The documentation is in an open PR.
For unresolved CFD-DEM, this will be coming this year. For Resolved CFD-DEM, it should be not too difficult also, but we have not yet ironed out the kinks of it.
Hope that answers your questions!
Best
Bruno
