### ISSUE TITLE
Handling of Dummy DOF in sharp solver

### ISSUE THREAD

**Issue by Luckabarbeau** [lethe-cfd/lethe#638]
Dummy DOFs are not part of the problem and have a value imposed based on the value of the solution in the proximity to them. At the moment, the proximity of two immersed boundaries may lead to a circular reference of the value imposed on these DOFs.

**Comment by DanW97** [comment]
Is this likely to cause a solver crash if circular references are present?

**Comment by Luckabarbeau** [comment]
Hello @DanW97 ,

This bug is now fixed. I forgot to remove the issue. The solution to this issue is as follows:

We check the number of particles that cut a given cell. If the number of particles is greater than 1, we don't use the sharp IB to impose the boundary condition on the Laplace equation for the dummy pressure inside the particles. This avoids the potential circular reference for the boundary condition when two particles cut the same cell. 

Cheers,

Lucka
