### ISSUE TITLE
Reading particle file in sharp solver

### ISSUE THREAD

**Issue by DanW97** [lethe-cfd/lethe#684]
Hi,

I've been trying to use the `load particles from file` option for the sharp solver, and I can't seem to get it to work, I'm not sure if I've missed something obvious or not. Following the docs, I set the type column to sphere and Lethe complains that a `<sphere> cannot be converted to a double` - I've also tried specifying individual IDs to each row and that instead results in a segfault.

I've attached the file used below:

[particles.zip](https://github.com/lethe-cfd/lethe/files/10440974/particles.zip)

Cheers,

Dan

**Comment by blaisb** [comment]
Dear @DanW97,
There is an example of a particle file here:
https://github.com/lethe-cfd/lethe/blob/master/applications_tests/gls_sharp_navier_stokes_3d/particles
It coincides with the following unit test:
https://github.com/lethe-cfd/lethe/blob/master/applications_tests/gls_sharp_navier_stokes_3d/load_particles_from_file_test.prm

Seems like that part is not very well documented yet. We will work to fix this soon
Best
Bruno

**Comment by DanW97** [comment]
Sorry for the late reply,

I see that 3 shape arguments must be provided, I had assumed that I could just set the one like in a prm file. It works now!

Cheers,

Dan
