### ISSUE TITLE
Messy sharp ib parameter section

### ISSUE THREAD

**Issue by Luckabarbeau** [lethe-cfd/lethe#710]
The sharp ib parameter section has become messy with the addition of multiple parameters in the last few months. The parameter should be redivided into smaller and clearer subsections.

**Comment by blaisb** [comment]
@Luckabarbeau Do you still plan to make this PR in the short term? It would be nice to be able to close this issue.

**Comment by Luckabarbeau** [comment]
Yes the PR is almost ready to be open
