### ISSUE TITLE
Boundary mesh generated is not high-order

### ISSUE THREAD

**Issue by acdaigneault** [lethe-cfd/lethe#727]
The boundary mesh files are not high-order, so we can't visualize it as a smooth mesh in Paraview. 
This is also the case when we use the subdivision parameter value as the highest order for FEM.
It would also be nice to have a parameter to only output one boundary mesh for a simulation since most of them don't have moving mesh. Actually, maybe it should be the default setting.

**Comment by blaisb** [comment]
I'll take care of this bug this week.

**Comment by acdaigneault** [comment]
> I'll take care of this bug this week.

Did you ? :p

**Comment by blaisb** [comment]
> > I'll take care of this bug this week.
> 
> Did you ? :p

I did not, but I will in a short horizon :)
