### ISSUE TITLE
Interpolated Void Fraction should be bounded to 1 for usage in drag and lift models

### ISSUE THREAD

**Issue by acdaigneault** [lethe-cfd/lethe#734]
If void fraction of cell is greater than 1, the Koch and Hill Drag Model do not work.
This is because of the `log(1 - cell_void_fraction)` in this part in the VANS Assembler :

```
if ((1 - cell_void_fraction) < 0.4)
        {
          f0 = (1 + 3 * sqrt((1 - cell_void_fraction) / 2) +
                (135.0 / 64) * (1 - cell_void_fraction) *
                  log(1 - cell_void_fraction) +
                16.14 * (1 - cell_void_fraction)) /
               (1 + 0.681 * (1 - cell_void_fraction) -
                8.48 * pow(1 - cell_void_fraction, 2) +
                8.16 * pow(1 - cell_void_fraction, 3));
        }
```

This results in -nan values in the RHS that crashes the solver.

EDIT: Even if not crashing the simulation, all interpolated void fraction value should be bounded to 1 before usage in any drag/lift models, as suggested in the comments of this issue.

**Comment by blaisb** [comment]
should be easy to solve by calculating the max(1-voidfraction,0)

**Comment by acdaigneault** [comment]
Yeah, but after +2hours of debugging about that, I keep it as a reminder for an easy PR :)

**Comment by acdaigneault** [comment]
Actually, the void fraction used in the models should all be limited to 1

**Comment by blaisb** [comment]
Absolutely. You are right!
The void fraction interpolated at the particle locations should all be bounded to one!
