### ISSUE TITLE
I finished build, but no executable works

### ISSUE THREAD

**Issue by xshen053** [lethe-cfd/lethe#825]
Hi, After I build lethe following guide

<img width="853" alt="image" src="https://github.com/lethe-cfd/lethe/assets/97472036/d06dc0d8-4c25-48a3-8b1d-3b88ce24a5ac">

I cannot execute anyone. Do you have any ideas what's wrong here?

**Comment by lpsaavedra** [comment]
Hi @xshen053 ,

This is not an application but a test. If you are trying to run an example with Lethe you should go to the applications folder within your build folder, where you can find all the executable. You can follow the instructions written [here](https://lethe-cfd.github.io/lethe/first_simulation.html).

**Comment by xshen053** [comment]
> Hi @xshen053 ,
> 
> This is not an application but a test. If you are trying to run an example with Lethe you should go to the applications folder within your build folder, where you can find all the executables. You can follow the instructions written [here](https://lethe-cfd.github.io/lethe/first_simulation.html).

Thank you, I ran it with example yesterday, but it showed segmentation fault again, I will double check today. Is it because it doesn't support arm? I am running it on arm-based server (not apple)

**Comment by xshen053** [comment]
> Hello @xshen053, Welcome to the Lethe communauty. To start which example are you trying to run with which application? Can you send us an example of the commend you are trying to run?

no problem, will send it today

**Comment by blaisb** [comment]
Dear @xshen053 have you managed to fix your issue? Otherwise, can you post the full error message you get.
Thanks
Bruno

**Comment by xshen053** [comment]
Hi, I plan to check it when I get a chance. Thanks!!

**Comment by blaisb** [comment]
@xshen053  I think I will close this issue.
