### ISSUE TITLE
Steady_BDF exit when initial CFL=0 

### ISSUE THREAD

**Issue by Luckabarbeau** [lethe-cfd/lethe#827]
While trying to relax the steady BDF solution process with a ramp in velocity, the simulation systematically stopped after the first time step, even if the residual error was not reached.

**Comment by blaisb** [comment]
@Luckabarbeau do you have a parameter file to reproduce the issue? I can make a fix

**Comment by Luckabarbeau** [comment]
A modified lid-driven cavity example can reproduce the error. 
`# Listing of Parameters
# ---------------------
# --------------------------------------------------
# Simulation and IO Control
#---------------------------------------------------

subsection simulation control
  set method = steady_bdf
  set adapt  = true
  # Maximum CFL value
  set max cfl = 1000
  # Tolerance at which the simulation is stopped
  set stop tolerance = 1e-10
  # Adaptative time step scaling
  set adaptative time step scaling = 1.05
  set time step                    = 0.001
end

#---------------------------------------------------
# Physical Properties
#---------------------------------------------------

subsection physical properties
  subsection fluid 0
    set kinematic viscosity = 0.000133333
  end
end

#---------------------------------------------------
# Mesh
#---------------------------------------------------

subsection mesh
  set type               = dealii
  set grid type          = hyper_cube
  set grid arguments     = 0 : 1 : true
  set initial refinement = 7
end

#---------------------------------------------------
# Timer
#---------------------------------------------------

subsection timer
  set type = iteration
end

# --------------------------------------------------
# Boundary Conditions
#---------------------------------------------------

subsection boundary conditions
  set number = 4
  subsection bc 0
    set id   = 0
    set type = noslip
  end
  subsection bc 1
    set id   = 1
    set type = noslip
  end
  subsection bc 2
    set id   = 2
    set type = noslip
  end
  subsection bc 3
    set id   = 3
    set type = function
    subsection u
      set Function expression = t
    end
    subsection v
      set Function expression = 0
    end
  end
end

#---------------------------------------------------
# FEM
#---------------------------------------------------

subsection FEM
  set velocity order = 1
  set pressure order = 1
end

# --------------------------------------------------
# Non-Linear Solver Control
#---------------------------------------------------

subsection non-linear solver
  set tolerance = 1e-7
  set verbosity = verbose
end

# --------------------------------------------------
# Linear Solver Control
#---------------------------------------------------

subsection linear solver
  set method                  = gmres
  set ilu preconditioner fill = 2
  set verbosity               = verbose
end`

**Comment by Luckabarbeau** [comment]
I rechecked this this morning. It was an error in the PRM. The time dependent boundary condition parameter was set to false.
