### ISSUE TITLE
WSL instructions should mention apt-get install

### ISSUE THREAD

**Issue by drwells** [lethe-cfd/lethe#872]
Hello! We are looking into using lethe here at UNC and a postdoc is installing it right now.

I happen to know that you can do `sudo apt-get install libdeal.ii-dev` but he did not, and the instructions for WSL are only for candi. It would be great to mention that it's possible to get deal.II via `apt` here instead of using candi in the WSL docs.

**Comment by blaisb** [comment]
Hey @drwells!
Glad to see you guys are interested in using it.
The only issue is that right now Lethe does not support deal.II 9.4 ( I need to update the installation instructions). 
Is libdeal.ii-dev compatible with 9.5 yet? @voferreira tried it out and it seemed to still install 9.4

**Comment by blaisb** [comment]
@voferreira  and @drwells I think we have a new ubuntu deal.II package now right?

**Comment by voferreira** [comment]
@blaisb Apparently yes. I will try it out right now.

**Comment by voferreira** [comment]
@blaisb It seems all clear. It is working well for Lethe installation, application tests, and applications. I just updated the WSL and regular installation procedures.

Thank you for pointing that out and for your interest in Lethe, @drwells!
