### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by ingchapa** [lethe-cfd/lethe#909]
Hi there. 
I pulled the docker image and I am having some issues.
First of all I expected the image to create a container that I could run interactively but I can't.
Secondly, when I try to run the example as explained here:

docker run --rm \
  -v $(pwd):/home/dealii \
  ghcr.io/lethe-cfd/lethe:master \
  lethe-fluid examples/incompressible_flow/2d_lid_driven_cavity/cavity.prm

I have the following error:

Exception on processing: 

--------------------------------------------------------
An error occurred in line <392> of file </home/dealii/lethe/source/core/utilities.cc> in function
    std::string get_last_value_of_parameter(const string&, const string&)
The violated condition was: 
    x_file.fail() == false
Additional information: 
    An input/output error has occurred. There are a number of reasons why
    this may be happening, both for reading and writing operations.
    
    If this happens during an operation that tries to read data: First,
    you may be trying to read from a file that doesn't exist or that is
    not readable given its file permissions. Second, deal.II uses this
    error at times if it tries to read information from a file but where
    the information in the file does not correspond to the expected
    format. An example would be a truncated file, or a mesh file that
    contains not only sections that describe the vertices and cells, but
    also sections for additional data that deal.II does not understand.
    
    If this happens during an operation that tries to write data: you may
    be trying to write to a file to which file or directory permissions do
    not allow you to write. A typical example is where you specify an
    output file in a directory that does not exist.

Stacktrace:
-----------
#0  /opt/lethe/lib/liblethe-core.so: get_last_value_of_parameter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#1  /opt/lethe/lib/liblethe-core.so: get_dimension(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#2  lethe-fluid: main

**Comment by blaisb** [comment]
Thank you for opening the issue :). We will take a look at this. The docker images are rarely used within our group, so I am unsure of their current status.

**Comment by ingchapa** [comment]
Hi Bruno. Thanks for the Reply.
I tried to use the docker because I have to select a software for CFD-DEM simulations for our group. There are many, so using docker makes it easier to test the features.
Kind Regards!
