### ISSUE TITLE
Some tables are not checkpointed

### ISSUE THREAD

**Issue by AmishgaAlphonius** [lethe-cfd/lethe#916]
Tables appearing in the finish_simulation() function are not checkpointed.
The tables in their respective physics that need to be checkpointed are listed below.
1. FD: 
      - [x] Forces
      - [x] Torques
      - [x] Errors

2. Heat Transfert:
      - [x] Errors
      - [x] Heat flux (postprocessing)
      - [x] Statistics table (postprocessing)

3. Tracer:
      - [x] Errors
      - [x] Statistics table (postprocessing)
      
4. VOF:
      - [x] Conservation monitoring
      - [x] Errors
      - [x] Barycenter (postprocessing)

5. Cahn Hilliard:
      - [x] Errors
      - [x] Statistics table (postprocessing)

- [x] Update restart tests with the new serialized tables

**Comment by blaisb** [comment]
@AmishgaAlphonius you take care of it or i take care of it?

**Comment by AmishgaAlphonius** [comment]
I can take care of it! I think I found them in utilities.h! It's just that I lost my anydesk connection midway 😅

**Comment by AmishgaAlphonius** [comment]
> @AmishgaAlphonius you take care of it or i take care of it? There are some pretty chill helper functions taht can help you with that
> 
> 

I can take care of it! I think I found them in utilities.h! It's just that I lost my anydesk connection midway 😅
